# Generated by Django 5.0.6 on 2024-05-15 19:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('manufacturer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=50)),
                ('model', models.CharField(max_length=50)),
                ('serial_number', models.CharField(max_length=50, unique=True)),
                ('location', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=20)),
                ('date_purchased', models.DateField()),
                ('warranty_expiration', models.DateField()),
                ('manufacturer', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='manufacturer.manufacturer')),
            ],
        ),
    ]
